### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by kinski76** [deckameron/Ti.Android.Geofence#1]
Hi I wondered if you would be kind enough to help me

Im using 7.0.1.GA

I am trying to use this module but everytime I add the example code for addGeoFences I get:

[WARN] :   W/System.err: java.lang.NumberFormatException: Unable to convert null
[WARN] :   W/System.err: 	at org.appcelerator.titanium.util.TiConvert.toInt(TiConvert.java:415)
[WARN] :   W/System.err: 	at ti.android.geofence.GeofenceModule.addGeofences(GeofenceModule.java:391)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:936)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1159)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:363)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:207)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5728)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[ERROR] :  TiExceptionHandler: (main) [11,8232] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [1,8233] - In undefined:256,16
[ERROR] :  TiExceptionHandler: (main) [0,8233] - Message: Uncaught Unable to convert null
[ERROR] :  TiExceptionHandler: (main) [0,8233] - Source:       geofence.addGeofences({
[ERROR] :  V8Exception: Exception occurred at undefined:256: Uncaught Unable to convert null
[ERROR] :  V8Exception: Unable to convert null

I have used your full example also and get the same result.

The part I didn't understand (whihc may cause this) is the libaries required

Where do I put the libraries you outline? 

Sorry these may be super simple questions but I am a bit of a noob:)

thank you very much in advance

**Comment by hansemannn** [comment]
The issue that if you are using `transitions`, you also need to use `dwellTime`. See [here](https://github.com/deckameron/Ti.Android.Geofence/blob/master/example/app.js#L49) for the missing property in the example and [here](https://github.com/deckameron/Ti.Android.Geofence/blob/master/android/src/ti/android/geofence/GeofenceModule.java#L391) for the native part. Should be easy to fix now. Either use a default value to the module source or add the `dwellTime` property as done for the other transitions.

**Comment by kinski76** [comment]
Thank you for your response its really appreciated.

I have added dwellTime as per example as test. 

 geofence.addGeofences({
        clearExistingFences : true,
        fences : [
            {
                "id" : "home",
               "latitude" : 37.422196,
				"longitude" :  -122.084004,
                "radius" : 100,
                "transitions" : [
                    geofence.GEOFENCE_TRANSITION_ENTER
                ],
                 "dwellTime" : 5 * 60 * 1000,
                //Notification 
               // "title" : "Google - Mountain View",
               // "sound" : "notification",
               // "accentColor" : "#E65100",
               // "type" : geofence.TYPE_PLACE_FENCE,
              //  "showGooglePlaceBigImage" : true,
                //"bigImage" : "https://lh3.googleusercontent.com/jOsYWBsr1muoRiMQFW9EU-ZqSCtfLBibu6S2g4nIbihP0SYL4Em6VD20WuieL1h5bBzbSrnIYVQZy5lhjUSR"
            }
        ]
    });



This gets me a tad further with fences being added but I now get:

[ERROR] :  TiExceptionHandler: (main) [73,10474] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,10474] - In undefined:220,16
[ERROR] :  TiExceptionHandler: (main) [0,10474] - Message: Uncaught java.lang.Integer cannot be cast to java.lang.Double
[ERROR] :  TiExceptionHandler: (main) [1,10475] - Source:       geofence.addGeofences({
[ERROR] :  V8Exception: Exception occurred at undefined:220: Uncaught java.lang.Integer cannot be cast to java.lang.Double
[ERROR] :  V8Exception: java.lang.Integer cannot be cast to java.lang.Double
[INFO] :   GEOFENCES_ADDED
[INFO] :   Ready to start monitoring!


I don't know java but looking at the source it seems that dwellTime is converted like the other values. Any idea what could be causing this next issue?

Thank you again for your input

**Comment by hansemannn** [comment]
Well, a bit error-reading can help already:
> **Integer** cannot be cast to **Double**

So maybe `(5 * 60 * 1000).toFixed(2)` will help. But this should ideally be done via the module source instead of the client.

**Comment by deckameron** [comment]
@hansemannn you are totally right! My bad!
I am sorry guys. I will fix it asap. :-) 

But, in the meanwhile,  please feel free to create a PR, that I will be glad to accept it.

**Comment by kinski76** [comment]
Would love to help by doing a PR but im not sure how to fix it....

As a note:

(5 * 60 * 1000).toFixed(2) doesnt work.... I get:

 :  TiExceptionHandler: (main) [1,4575] - Source:       geofence.addGeofences({
[ERROR] :  V8Exception: Exception occurred at undefined:244: Uncaught Invalid int: "300000.00"
[ERROR] :  V8Exception: Invalid int: "300000.00"



Neither does just using an Interger. If i use an int i get back:

 Uncaught java.lang.Integer cannot be cast to java.lang.Double
[ERROR] :  V8Exception: java.lang.Integer cannot be cast to java.lang.Double

**Comment by deckameron** [comment]
@kinski76 could you please try [this new version](https://github.com/deckameron/Ti.Android.Geofence/blob/master/android/dist/ti.android.geofence-android-1.0.1.zip?raw=true)?

**Comment by kinski76** [comment]
Hi

Many thanks for this. That works now with the example you provide!:) 

One small gotcha is that dwellTime is ommited from the first fence in your example. Therefore it throws up that double error again because it needs it to be present:) Just mention so other people dont get hit with it.

thank you very much for the time you have spent in creating this module:)

**Comment by deckameron** [comment]
Hi @kinski76 

I think [this new version](https://github.com/deckameron/Ti.Android.Geofence/blob/master/android/dist/ti.android.geofence-android-1.0.2.zip?raw=true) fixes the gotcha. :-)

**Comment by kinski76** [comment]
brilliant...thank you:)
