### ISSUE TITLE
Disabling notifications

### ISSUE THREAD

**Issue by malakodas** [deckameron/Ti.Android.Geofence#2]
Hi,

is there any way to disable notifications from arriving on enter/exit/dwell events?

Looking at the code seems that they always default to default text/message/images, but still curious is there any way to hack it.

Thanks

**Comment by deckameron** [comment]
hi @malakodas 
Could you try using [this version](https://github.com/deckameron/Ti.Android.Geofence/blob/master/android/dist/ti.android.geofence-android-1.0.3.zip?raw=true).
```javascript
{
	"id" : "google",
	"latitude" : 37.422196,
	"longitude" : -122.084004,
	"radius" : 1000,
	"transitions" : [
		geofence.GEOFENCE_TRANSITION_ENTER
	],
	//Notification 
	canNotify : false
},
```
